name: Windows-Litemanager
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    # Corrected "windows-letest" to "windows-latest"
    runs-on: windows-latest

    steps:
    - name: Downloading & installing Essentials
      run: |
        # This command is now on a single line to fix the YAML syntax error.
        Invoke-WebRequest -Uri "https://gitlab.com/chmod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

    - name: Connect to LiteManager
      run: cmd /c show.bat

    - name: Time Counter
      run: cmd /c loop.bat
